spring.application.name=my-first-api

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${APP_JWT_SECRET:a-very-long-secret-key-that-is-at-least-32-characters}