spring.application.name=my-first-api

# 1. FORCE THE DIALECT (This prevents the current error)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# 3. Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# 4. Port and JWT
server.port=${PORT:8080}
app.jwt.secret=${JWT_SECRET}