spring.application.name=my-first-api

# Force Spring to use the environment variables
# spring.datasource.url=${DB_URL}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mytaskdb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Lek!@#227}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JWT Secret - Rename the key to avoid the circular error
# We use 'app.jwt.secret' as the property name, which pulls from 'JWT_SECRET' environment variable
app.jwt.secret=${JWT_SECRET:my-very-long-secret-key-at-least-32-characters-long}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Port handling for Render
server.port=${PORT:8080}
