# LOCAL SETTINGS (Eclipse)
spring.datasource.url=jdbc:postgresql://localhost:5432/mytaskdb
spring.datasource.username=postgres
spring.datasource.password=Lek!@#227
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=local-secret-key-at-least-32-characters-long